create table
  public.cities (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    population bigint not null,
    constraint cities_pkey primary key (id)
  ) tablespace pg_default;